In [11]:
import pickle

from etl import UserGenerator
from feature_engineer import FeatureEngineer


def get_model():
    with open('models/model_rf.pkl', 'rb') as f:
        model = pickle.load(f)
    return model

def get_etl_data():
    user_generator = UserGenerator(n_samples=100000)
    df = user_generator.create_dataset()
    return df

def get_data():
    df = get_etl_data()
    feature_engineer = FeatureEngineer(df)
    df = feature_engineer.create_features()
    return df

def predict(model, df):
    return model.predict(df)

def save_prediction(df, prediction):
    df["prediction"] = prediction
    df["prediction"] = df["prediction"].astype(int)
    df["prediction"] = df["prediction"].map({0: "No", 1: "Si"})
    df.to_csv('predictions/predictions.csv', index=False)
    return df

In [2]:
model = get_model()

In [3]:
model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['days_since_registration',
                                                   'total_purchases',
                                                   'avg_order_value',
                                                   'last_purchase_days',
                                                   'sessions_last_30_days',
                                                   'time_on_site_minutes',
                                                   'pages_per_session',
                                                   'cart_abandonment_rate',
                                                   'purchase_frequency']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value='Unknown',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['age_group', 'location',
                                                   'device_type',
                                                   'subscription_type'])])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [4]:
df = get_data()

Generando datos sintéticos de usuarios para targeting de promociones...
✅ Agregados 4959 valores nulos en 'age_group' (5.0%)
✅ Agregados 2910 valores nulos en 'location' (3.0%)
✅ Agregados 2028 valores nulos en 'device_type' (2.0%)
✅ Agregados 930 valores nulos en 'subscription_type' (1.0%)
✅ Agregados 7939 valores nulos en 'avg_order_value' (8.0%)
✅ Agregados 14967 valores nulos en 'last_purchase_days' (15.0%)
✅ Agregados 9889 valores nulos en 'time_on_site_minutes' (10.0%)
✅ Agregados 9867 valores nulos en 'pages_per_session' (10.0%)
✅ Agregados 12010 valores nulos en 'cart_abandonment_rate' (12.0%)
✅ Agregados 7978 valores nulos en 'purchase_frequency' (8.0%)

In [5]:
df

,user_id,age_group,location,device_type,subscription_type,days_since_registration,total_purchases,avg_order_value,last_purchase_days,sessions_last_30_days,time_on_site_minutes,pages_per_session,cart_abandonment_rate,purchase_frequency,total_purchases_per_day,days_between_first_and_last_purchase,bucket_avg_order_value
0,USER-000001,18-25,Mendoza,Mobile,Free,38,6,341.58,139.0,2,NaN,1.6,0.075,4.74,0.157895,-101.0,high
1,USER-000002,26-35,Buenos Aires,Mobile,Basic,246,34,215.56,114.0,18,34.1,17.5,0.607,4.15,0.138211,132.0,medium
2,USER-000003,36-45,Buenos Aires,Mobile,Enterprise,284,21,NaN,97.0,3,43.7,NaN,0.212,2.22,0.073944,187.0,NaN
3,USER-000004,36-45,Cordoba,Tablet,Free,343,35,153.66,160.0,19,106.4,7.9,0.154,3.06,0.102041,183.0,low
4,USER-000005,18-25,Buenos Aires,Mobile,Free,330,14,434.58,97.0,8,55.0,16.8,NaN,NaN,0.042424,233.0,high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,USER-099996,26-35,Buenos Aires,Mobile,Free,129,20,380.17,141.0,24,71.7,9.1,0.525,4.65,0.155039,-12.0,high
99996,USER-099997,18-25,Otros,Desktop,Free,51,17,464.09,171.0,8,104.3,3.8,0.142,10.00,0.333333,-120.0,high
99997,USER-099998,36-45,Otros,Desktop,Basic,307,44,436.82,8.0,2,87.6,10.2,0.203,4.30,0.143322,299.0,high
99998,USER-099999,26-35,Cordoba,Mobile,Basic,124,42,183.75,179.0,15,NaN,7.8,0.085,10.16,0.338710,-55.0,medium
99999,USER-100000,46-55,NaN,Mobile,Free,154,24,461.75,64.0,25,31.1,11.5,0.431,4.68,0.155844,90.0,high

In [12]:
prediction = predict(model, df)

In [13]:
prediction

array([1, 0, 1, ..., 1, 0, 0], shape=(100000,))

In [8]:
prediction_array = prediction[:, 1]

In [14]:
save_prediction(df, prediction)

,user_id,age_group,location,device_type,subscription_type,days_since_registration,total_purchases,avg_order_value,last_purchase_days,sessions_last_30_days,time_on_site_minutes,pages_per_session,cart_abandonment_rate,purchase_frequency,total_purchases_per_day,days_between_first_and_last_purchase,bucket_avg_order_value,prediction
0,USER-000001,18-25,Mendoza,Mobile,Free,38,6,341.58,139.0,2,NaN,1.6,0.075,4.74,0.157895,-101.0,high,Si
1,USER-000002,26-35,Buenos Aires,Mobile,Basic,246,34,215.56,114.0,18,34.1,17.5,0.607,4.15,0.138211,132.0,medium,No
2,USER-000003,36-45,Buenos Aires,Mobile,Enterprise,284,21,NaN,97.0,3,43.7,NaN,0.212,2.22,0.073944,187.0,NaN,Si
3,USER-000004,36-45,Cordoba,Tablet,Free,343,35,153.66,160.0,19,106.4,7.9,0.154,3.06,0.102041,183.0,low,No
4,USER-000005,18-25,Buenos Aires,Mobile,Free,330,14,434.58,97.0,8,55.0,16.8,NaN,NaN,0.042424,233.0,high,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,USER-099996,26-35,Buenos Aires,Mobile,Free,129,20,380.17,141.0,24,71.7,9.1,0.525,4.65,0.155039,-12.0,high,No
99996,USER-099997,18-25,Otros,Desktop,Free,51,17,464.09,171.0,8,104.3,3.8,0.142,10.00,0.333333,-120.0,high,No
99997,USER-099998,36-45,Otros,Desktop,Basic,307,44,436.82,8.0,2,87.6,10.2,0.203,4.30,0.143322,299.0,high,Si
99998,USER-099999,26-35,Cordoba,Mobile,Basic,124,42,183.75,179.0,15,NaN,7.8,0.085,10.16,0.338710,-55.0,medium,No
99999,USER-100000,46-55,NaN,Mobile,Free,154,24,461.75,64.0,25,31.1,11.5,0.431,4.68,0.155844,90.0,high,No